### PR TITLE
Restore link to favicon.ico (bnc#917570)

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by vuntz** [comment]
Not tested, but I assume you did. +1

**Comment by toabctl** [comment]
Works for me. merging...

**Comment by toabctl** [comment]
@dirkmueller needs cherry-pick for juno branch.

**Comment by thutterer** [comment]
Does not work with Chrome/Chromium.
See https://bugzilla.suse.com/show_bug.cgi?id=917570#c2

**Pull request merged**
