### PR TITLE
Require login to access help pages

### PR DESCRIPTION
**Pull request by toabctl**
https://bugzilla.suse.com/show_bug.cgi?id=916033
(cherry picked from commit 50130b66706902875a6c21fcdc331a92537751bb)

### CODE REVIEW

**Comment by dirkmueller** [comment]
can you please change the summary to include the bug reference like " (bnc#916033)"

**Comment by toabctl** [comment]
> can you please change the summary to include the bug reference like " (bnc#916033)"

Done in https://github.com/toabctl/horizon-suse-theme/commit/980cb9bf1df9180f9db827c57fd7c0a4fcc5d0bf

**Comment by vuntz** [comment]
Works, +1

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
