### PR TITLE
Adapt the SUSE Theme to OpenStack Kilo

### PR DESCRIPTION
**Pull request by aplanas**
Cheap version of SUSE theme ported to Kilo.  Useful as a starting point for the real work.

### CODE REVIEW

**Comment by dirkmueller** [comment]
+1

**Comment by vuntz** [comment]
Will test it once I have horizon deployed.

Small typo in the commit message: addapt -> adapt

**Comment by toabctl** [comment]
+1 (but not tested)

**Comment by aplanas** [comment]
- Fix commit message

**Comment by vuntz** [comment]
Tested, thanks!

**Pull request merged**
