### PR TITLE
Convert and rename logo images (SCRD-36)

### PR DESCRIPTION
**Pull request by cmurphy**
Horizon now looks for *.svg files instead of *.png files for the theme
logos[1]. This patch converts the existing PNG files to SVG format and
renames them to have the matching extension.

[1] https://docs.openstack.org/releasenotes/horizon/ocata.html#upgrade-notes

### CODE REVIEW

**Review by nicolasbock — APPROVED** [review]

**Comment by vuntz** [comment]
Would it make sense to not convert the png to a svg, but use a real svg? If yes, @kwwii probably has this somewhere.

**Comment by cmurphy** [comment]
@vuntz I had no idea where the original was stored, if it's available then that would definitely be better.

**Comment by cmurphy** [comment]
@kwwii any idea where I could find these originals?

@vuntz in the absence of the original logos I think this still fulfills the requirements of the Jira task, and when it comes time to release Cloud 8 I assume the design team will have new media we can work with.

**Comment by cmurphy** [comment]
@vuntz I spoke with @kwwii, the originals were made in Photoshop (which doesn't produce vector graphics) so he would have to create SVG images from scratch, and since this is just an intermediate step that won't be released to customers we agree that the converted images are fine for now.

**Pull request merged**
