### PR TITLE
Update logos to replace copyright symbol with registered trademark

### PR DESCRIPTION
**Pull request by kwwii**

### CODE REVIEW

**Comment by aplanas** [comment]
A note for reviewers: the difference is the change from (C) to (R)

**Comment by rsalevsky** [comment]
+1

@kwwii Should we update also the logo for crowbar?

**Comment by tboerger** [comment]
> @kwwii Should we update also the logo for crowbar?

Of course, I think @kwwii will commit the changes.

**Comment by tboerger** [comment]
:+1:

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
