### PR TITLE
Update favicon with a retina + openstack version

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by toabctl** [comment]
According to https://msdn.microsoft.com/en-us/library/ie/gg491740(v=vs.85).aspx, 24x24, 48x48 and also 64x64 would be nice to have.
We should also think about adding some pngs with higher resolutions (see http://stackoverflow.com/questions/2268204/favicon-dimensions). But that's another thing.

**Comment by vuntz** [comment]
@dirkmueller hrm, I thought the design team didn't want an openstack-specific version?

@kwwii is this fine?

**Comment by dirkmueller** [comment]
@vuntz didn't read that feedback in time. For me this still makes sense, it is otherwise very hard to distinguish crowbar and openstack horizon tabs.

**Comment by toabctl** [comment]
@kwwii can you please comment on this? Do we want a OpenStack specific icon for Cloud 6?

**Comment by kwwii** [comment]
Having different fav icons might be of benefit to the user but a proper concept needs to be designed before this could happen as it would need to apply to all of our products.

**Comment by dirkmueller** [comment]
@kwwii ok. can you provide a SUSE favicon that has a retina version included? it kind of looks ugly if you are using multiple SUSE products in the browser that all of them have the same icon that looks pixelated like from the 80ies.

**Comment by dirkmueller** [comment]
@vuntz this is the updated icon now from Ken, ok to merge?

**Comment by vuntz** [comment]
Sure.

**Comment by aplanas** [comment]
this is 16x16, I was under impression that 32 and 48 are needed, or even bigger: http://stackoverflow.com/questions/4014823/does-a-favicon-have-to-be-32x32-or-16x16

**Comment by aplanas** [comment]
ah jesus, with-a-retina, not a retina-size icon, sorry

**Pull request merged**
