### PR TITLE
Adjust SUSE theme to Mitaka

### PR DESCRIPTION
**Pull request by aplanas**

### CODE REVIEW

**Comment by aplanas** [comment]
cc @toabctl

**Comment by toabctl** [comment]
+1

**Comment by vuntz** [comment]
Do you have this running somewhere so that we can check it live? :-)

**Comment by aplanas** [comment]
@vuntz my bad: http://dashboard.vi6.cloud.suse.de

**Comment by vuntz** [comment]
+1

@kwwii do you have some quick time to update the logo to mention Cloud 7? https://github.com/SUSE-Cloud/horizon-suse-theme/blob/master/themes/suse/img/logo-splash.png

**Pull request merged**
